# save as .github/workflows/update_livetv.yml
name: Update LiveTV Playlist

on:
  schedule:
    - cron: '0 3 * * *'  # Run daily at 3 AM UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'livetv.py'
      - '.github/workflows/update_livetv.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycryptodome

    - name: Generate encrypted playlist
      env:
        LIVETV_BASE_URL: ${{ secrets.LIVETV_BASE_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      run: python livetv.py

    - name: Upload playlist artifact
      uses: actions/upload-artifact@v3
      with:
        name: livetv-playlist
        path: livetv_playlist.m3u
        retention-days: 1

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add livetv_playlist.m3u
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Update LiveTV playlist [skip ci]" && \
           git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
